language: php

dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - composer validate
  - vendor/bin/php-cs-fixer fix --dry-run --diff
  - vendor/bin/phpstan analyse --memory-limit=-1 --no-progress --no-interaction
  - vendor/bin/phpunit --coverage-clover=coverage.xml
